### ISSUE TITLE
Choices seem too round.

### ISSUE THREAD

**Issue by Animesh-Ghosh** [Prajeshpuri/GDG-angular#1]
Choice List items seem to have too large `border-radius`. 
![image](https://user-images.githubusercontent.com/34956994/87021930-6988ad00-c1f3-11ea-976d-e9d19f1716d2.png)

I am suggesting that `border-radius` be specified using `em` or `rem` units and also have a `font-size` specified on the `:root` element in the global `style.css`.

**Comment by Animesh-Ghosh** [comment]
![image](https://user-images.githubusercontent.com/34956994/87022907-bf118980-c1f4-11ea-8b8d-c20d42cfd456.png)
Modifies some style, this is what it looks like. We can ask around if it would look better from others.

**Comment by Prajeshpuri** [comment]
I made the first beta same as your then I think more rounded corners will be more attractive. No problem we can decide which one looks good.

**Comment by Prajeshpuri** [comment]
Roundness removed !!
